/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : gpio_pins.c
**     Project     : twrk21d50m-pin
**     Processor   : MK21DN512VMB5
**     Component   : fsl_gpio
**     Version     : Component 01.106, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-06-08, 17:51, # CodeGen: 7
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file gpio_pins.c
** @version 01.00
*/         
/*!
**  @addtogroup gpio_pins_module gpio_pins module documentation
**  @{
*/

/* MODULE gpio_pins. */

#include "gpio_pins.h"


gpioInputPinConfig_t switchPins[] = {
    {
        .gpioPort = gpioPort_E_c,
        .gpioPin = 4,
        .pullSelect = pinPull_Up_c,
        .interruptSelect = pinInt_FallingEdge_c
    },
    {
        .gpioPort = gpioPort_E_c,
        .gpioPin = 3,
        .pullSelect = pinPull_Up_c,
        .interruptSelect = pinInt_FallingEdge_c
    },
/* Exclude kGpioSW3 and kGpioSW4 in order to enable FSCI Host demo app with FRDM_K64F */
    {
        .gpioPort = gpioPort_D_c,
        .gpioPin = 1,
        .pullSelect = pinPull_Up_c,
        .interruptSelect = pinInt_FallingEdge_c
    },
    {
        .gpioPort = gpioPort_A_c,
        .gpioPin = 19,
        .pullSelect = pinPull_Up_c,
        .interruptSelect = pinInt_FallingEdge_c
    }
};


gpioOutputPinConfig_t ledPins[] = {
    {
        .gpioPort = gpioPort_D_c,
        .gpioPin = 4,
        .outputLogic = 1,
        .slewRate = pinSlewRate_Slow_c,
        .driveStrength = pinDriveStrength_Low_c
    },
    {
        .gpioPort = gpioPort_D_c,
        .gpioPin = 5,
        .outputLogic = 1,
        .slewRate = pinSlewRate_Slow_c,
        .driveStrength = pinDriveStrength_Low_c
    },
    {
        .gpioPort = gpioPort_D_c,
        .gpioPin = 6,
        .outputLogic = 1,
        .slewRate = pinSlewRate_Slow_c,
        .driveStrength = pinDriveStrength_Low_c
    },
    {
        .gpioPort = gpioPort_D_c,
        .gpioPin = 7,
        .outputLogic = 1,
        .slewRate = pinSlewRate_Slow_c,
        .driveStrength = pinDriveStrength_Low_c
    }
};

const gpioOutputPinConfig_t mXcvrSpiCsCfg = {
    .gpioPort = gpioPort_B_c,
    .gpioPin = 10,
    .outputLogic = 1,
    .slewRate = pinSlewRate_Fast_c,
    .driveStrength = pinDriveStrength_Low_c
};

const gpioOutputPinConfig_t mXcvrResetPinCfg = {
    .gpioPort = gpioPort_B_c,
    .gpioPin = 19,
    .outputLogic = 1,
    .slewRate = pinSlewRate_Fast_c,
    .driveStrength = pinDriveStrength_Low_c
};

const gpioInputPinConfig_t mXcvrIrqPinCfg = {
    .gpioPort = gpioPort_B_c,
    .gpioPin = 3,
    .pullSelect = pinPull_Disabled_c,
    .interruptSelect = pinInt_Disabled_c
};

gpioInputPinConfig_t  gRf_Confirm = {
    .gpioPort = gpioPort_C_c,
    .gpioPin = 5,
    .pullSelect = pinPull_Down_c,
    .interruptSelect = pinInt_EitherEdge_c
};

gpioOutputPinConfig_t gRf_Active  = {
    .gpioPort = gpioPort_C_c,
    .gpioPin = 7,
    .outputLogic = 0,
    .slewRate = pinSlewRate_Fast_c,
    .driveStrength = pinDriveStrength_Low_c
};

gpioOutputPinConfig_t gRf_Status  = {
    .gpioPort = gpioPort_C_c,
    .gpioPin = 6,
    .outputLogic = 0,
    .slewRate = pinSlewRate_Fast_c,
    .driveStrength = pinDriveStrength_Low_c
};
